version: '3'

services:
  mongo:
    container_name: mongo
    image: mongo:3.2.21
    ports:
      - 27017:27017

  app:
    container_name: on_this_day
    environment:
    - DB_HOST=mongo
    build: .
    ports:
      - 9000:9000
    depends_on:
      - mongo

