version: "3"

services:
  mongodb:
    image: mongo:4.2.2
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db

  app:
    build: .
    container_name: onthisday
    environment:
      - MONGODB_HOST=mongodb
    ports:
      - 9000:9000
    depends_on:
      - mongodb
